BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb "
BBFILES += "${LAYERDIR}/recipes-*/*/*.bbappend "
BBFILES += "${LAYERDIR}/recipes-*/*.bb "
BBFILES += "${LAYERDIR}/recipes-*/*.bbappend "

BBFILE_COLLECTIONS += "rpilinux"
BBFILE_PATTERN_rpilinux = "^${LAYERDIR}/"
BBFILE_PRIORITY_rpilinux = "6"

LAYERSERIES_COMPAT_rpilinux = "walnascar"

ENABLE_SPI_BUS="1"
ENABLE_I2C="1"

KERNEL_MODULE_AUTOLOAD:rpi += "i2c-dev i2c-bcm2835"
KERNEL_MODULE_AUTOLOAD:rpi += "spidev spi-bcm2835"

